### ISSUE TITLE
setup: upgrading to `adage==0.10.2` breaks yadage workflows

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-workflow-engine-yadage#220] opened 2022-02-02 10:49 UTC
After upgrading to`adage==0.10.2`, it's required to upgrade `networkx>=2.4`. This makes our yadage workflows fail on the workflow engine side. The jobs finished successfully but there's a problem afterward, perhaps when the visualization files are generated.

```console
$ reana-client logs -w hello-yadage.1
==> Workflow engine logs
Workflow exited unexpectedly.
Command 'convert -delay 50 $(ls /var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/*.png|sort) /var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/workflow.gif' returned non-zero exit status 1.
2022-02-02 10:08:28,350 | yadage.creators | MainThread | INFO | initializing workflow with initdata: {'helloworld': 'code/helloworld.py', 'inputfile': 'data/names.txt', 'sleeptime': 0} discover: True relative: True
2022-02-02 10:08:28,350 | adage.pollingexec | MainThread | INFO | preparing adage coroutine.
2022-02-02 10:08:28,350 | adage | MainThread | INFO | starting state loop.
2022-02-02 10:08:28,387 | yadage.wflowview | MainThread | INFO | added </init:0|defined|unknown>
2022-02-02 10:08:28,562 | yadage.wflowview | MainThread | INFO | added </helloworld:0|defined|unknown>
2022-02-02 10:08:28,655 | adage.pollingexec | MainThread | INFO | submitting nodes [</init:0|defined|known>]
2022-02-02 10:08:28,709 |       pack.init.step |   INFO | publishing data: <TypedLeafs: {'helloworld': '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/code/helloworld.py', 'inputfile': '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/data/names.txt', 'sleeptime': 0}>
2022-02-02 10:08:28,709 | adage | MainThread | INFO | unsubmittable: 0 | submitted: 0 | successful: 0 | failed: 0 | total: 2 | open rules: 0 | applied rules: 2
2022-02-02 10:08:43,824 | adage.node | MainThread | INFO | node ready </init:0|success|known>
2022-02-02 10:08:43,824 | adage.pollingexec | MainThread | INFO | submitting nodes [</helloworld:0|defined|known>]
2022-02-02 10:08:44,196 | reana-workflow-engine-yadage | MainThread | INFO | Submitted job with id: ec9c6a38-5da1-4abf-92f2-1d51c8884aae
2022-02-02 10:08:44,196 | adage | MainThread | INFO | unsubmittable: 0 | submitted: 0 | successful: 1 | failed: 0 | total: 2 | open rules: 0 | applied rules: 2
2022-02-02 10:08:59,379 | adage.node | MainThread | INFO | node ready </helloworld:0|success|known>
2022-02-02 10:08:59,379 | adage | MainThread | INFO | unsubmittable: 0 | submitted: 0 | successful: 2 | failed: 0 | total: 2 | open rules: 0 | applied rules: 2
2022-02-02 10:09:14,398 | adage.controllerutils | MainThread | INFO | no nodes can be run anymore and no rules are applicable
2022-02-02 10:09:14,399 | adage.controllerutils | MainThread | INFO | no nodes can be run anymore and no rules are applicable
2022-02-02 10:09:14,399 | adage | MainThread | INFO | unsubmittable: 0 | submitted: 0 | successful: 2 | failed: 0 | total: 2 | open rules: 0 | applied rules: 2
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
Error: <stdin>: syntax error in line 1 near '{'
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_00.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_01.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_02.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_03.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_04.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_05.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_06.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_07.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_08.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_09.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_10.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_11.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_12.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_13.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_14.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_15.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_16.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_17.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_18.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_19.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_20.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_21.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_22.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_23.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_24.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_25.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_26.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_27.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_28.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_29.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_30.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_31.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_32.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_33.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_34.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_35.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_36.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_37.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_38.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_39.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: improper image header `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/track/dag_40.png' @ error/png.c/ReadPNGImage/4092.
convert-im6.q16: no images defined `/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/_yadage/adage/workflow.gif' @ error/convert.c/ConvertImageCommand/3258.
2022-02-02 10:09:15,113 | yadage.steering_api | MainThread | INFO | done. dumping workflow to disk.
Couldn't import dot_parser, loading of dot files will not be possible.




==> Job logs
==> Step: helloworld
==> Workflow ID: 1bb4b9de-3d77-452e-8d59-c49be4086293
==> Compute backend: Kubernetes
==> Job ID: reana-run-job-d300724b-021e-4893-b276-8a18026766d5
==> Docker image: python:2.7-slim
==> Command: python "/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/code/helloworld.py" --sleeptime 0 --inputfile "/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/data/names.txt" --outputfile "/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/helloworld/greetings.txt"
==> Status: finished
==> Finished: 2022-02-02T10:08:59
==> Logs:
job: :
 2022-02-02T10:08:44 INFO     Parameters: inputfile=/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/data/names.txt outputfile=/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/1bb4b9de-3d77-452e-8d59-c49be4086293/helloworld/greetings.txt sleeptime=0.0


Completed
```

With `adage==0.10.1` (and `networkx==1.11`) everything runs as usual.

Adage release: https://github.com/yadage/adage/releases/tag/v0.10.2

**Comment by mvidalgarcia** [comment] 2022-02-02 10:50
@matthewfeickert @lukasheinrich maybe you have some ideas on what's going on here?

**Comment by matthewfeickert** [comment] 2022-02-02 15:02
> With `adage==0.10.1` (and `networkx==1.11`) everything runs as usual.

From the job logs it looks like you're running `python:2.7-slim`. We don't support Python 2, and haven't for a while, but it was only in `adage` `v0.10.2` that this got properly reflected with [`python_requires`](https://github.com/yadage/adage/blob/ff47d3a67300029e5e444a250ba6eb6208cae927/setup.cfg#L37) (to keep from breaking Python 2 installs).


> After upgrading to`adage==0.10.2`, it's required to upgrade `networkx>=2.4`

The reason for setting lower bounds on `networkx` is to allow for Python 3.9+ support. c.f.
* https://github.com/yadage/adage/issues/16
* https://github.com/yadage/adage/pull/18

for more details.

**Comment by matthewfeickert** [comment] 2022-02-02 15:17
It also looks like your `install_requires` has additional situations in which you'd create conflicts from pinning dependencies 

https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/setup.py#L43-L55

so I'm not sure how `pip-tools` is resolving those in anyway that wouldn't give a breaking build if you installed `adage==0.10.2`.

**Comment by mvidalgarcia** [comment] 2022-02-02 15:31
I'm not running Python2, that's just the container were the job is being run. The [Yadage workflow engine uses Python 3.8](https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/Dockerfile#L8).

**Comment by matthewfeickert** [comment] 2022-02-02 16:05
> I'm not running Python 2, that's just the container where the job is being run. The [Yadage workflow engine uses Python 3.8](https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/Dockerfile#L8).

:+1: and I see that you're using `pip-tools` (also :+1:)

https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/requirements.txt#L5

to produce a requirements lockfile that has

https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/requirements.txt#L7
https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/requirements.txt#L32

So unless you're also updating your `setup.py` to avoid having pins like

https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/setup.py#L47

there's never going to be a way for you to have `pip-tools` properly resolve things where you're giving `pip-tools` a scenario with `adage>=0.10.2` to resolve.

Am I missing something here about what you're doing?

**Comment by mvidalgarcia** [comment] 2022-02-02 16:44
> Or are you saying that you're already removing the pins and then letting `pip-tools` do the resolution and **then** you're getting the bug?

Exactly this. Sorry for the misunderstanding.

**Comment by matthewfeickert** [comment] 2022-02-02 16:49
> Exactly this. Sorry for the misunderstanding.

Can you give me a branch that has a minimal failing example?

**Comment by matthewfeickert** [comment] 2022-02-02 18:29
> Couldn't import dot_parser, loading of dot files will not be possible.

@mvidalgarcia Sorry can you also try installing `pydot`? [`pydot2` hasn't released since 2014](https://pypi.org/project/pydot2/#history) and doesn't support Python 3.9+ (c.f. https://github.com/yadage/adage/pull/17).

My guess is from

https://github.com/reanahub/reana-workflow-engine-yadage/blob/ac194f6d2972ea77642ba5d3f10d2da2173fff0e/setup.py#L49-L50

this is because of us (or at least the `yadage[viz]` extra being a bit broken at the moment). Can you try again with adding `pydot` in and then if that works try removing `pydot2`?

**Comment by mvidalgarcia** [comment] 2022-02-03 15:28
@matthewfeickert Your diff did the trick! Indeed it seems the error was caused by `pydot2`. I'm running some examples locally and they're working now, no `adage` pinning needed. I'll push my changes soon to [this PR](https://github.com/reanahub/reana-workflow-engine-yadage/pull/219). 

Thanks for the quick reaction!

**Comment by matthewfeickert** [comment] 2022-02-03 18:17
> Your diff did the trick! Indeed it seems the error was caused by `pydot2`. I'm running some examples locally and they're working now, no `adage` pinning needed. I'll push my changes soon to [this PR](https://github.com/reanahub/reana-workflow-engine-yadage/pull/219).

@mvidalgarcia Great! :) Yeah, sorry about all of this as this is indeed the fault of recent yadage org stuff as we've been trying to clean things up. Specifically, when going to [`adage` `v0.10.2`](https://github.com/yadage/adage/releases/tag/v0.10.2) we switched to using the networkx `v2.X` API (https://github.com/yadage/adage/pull/18) and the `networkx` `v2` API change brought with it a lot of related changes for `graphviz` visualization (c.f. https://github.com/networkx/networkx/pull/2272).

On the upside though, I've made an [`adage` `v0.10.3`](https://github.com/yadage/adage/releases/tag/v0.10.3) and am working on getting a `yadage` `v0.20.1` which should have this visualization stuff sorted out in their `viz` extras so you won't need to mess with any of the stuff in `setup.py` that currently has the `# FIXME needed only if yadage visuale=True.` comment (c.f. https://github.com/yadage/adage/pull/25, https://github.com/yadage/yadage/pull/108). You should be able to just do `yadage[viz]`. :+1: I'll still work on getting `pydotplus` removed though (https://github.com/yadage/yadage/issues/106).

**Comment by matthewfeickert** [comment] 2022-02-07 18:08
The regression seen in https://github.com/reanahub/reana-workflow-engine-yadage/pull/219 is caused by https://github.com/yadage/yadage/issues/116.

**Closed** 2022-02-07 19:42 UTC
Labels: type/bug
